# Generated by Django 5.0.7 on 2024-08-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак Преподавателя'),
        ),
    ]
