# Generated by Django 5.0.7 on 2024-08-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер вопроса'),
        ),
    ]
