# Generated by Django 5.0.7 on 2024-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_test', '0002_answer_answer_number_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_number',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_variant',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер вопроса'),
        ),
    ]
