# Generated by Django 5.0.7 on 2024-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_test', '0003_remove_answer_answer_number_answer_answer_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=600, verbose_name='Текст вопроса'),
        ),
    ]
